language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libv8-dev
      - libgdal1h
      - gdal-bin
      - libproj-dev
      - libhdf5-dev 
      - libhdf5-serial-dev
      - libgdal-dev

env:
- _R_CHECK_FORCE_SUGGESTS_=FALSE

notifications:
  email:
    on_success: change
    on_failure: change
