language: r
sudo: required
cache: packages
dist: trusty

apt_packages:
  - libudunits2-dev

r_github_packages:
  - jimhester/covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev netcdf-bin libv8-dev

compiler:
  - clang

after_success:
  - Rscript -e 'covr::codecov()'

env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - _R_CHECK_FORCE_SUGGESTS_=FALSE

notifications:
  email:
    on_success: never
    on_failure: never
